services:
  tvshows_config.route_subscriber:
    class: Drupal\tvshows_config\Routing\RouteSubscriber
    tags:
      - { name: event_subscriber }
  tvshows_config.season_helper:
    class: Drupal\tvshows_config\Services\SeasonHelper
    arguments: ["@entity_type.manager"]
  tvshows_config.episode_helper:
    class: Drupal\tvshows_config\Services\EpisodeHelper
    arguments: []
  tvshows_config.taxonomy_helper:
    class: Drupal\tvshows_config\Services\TaxonomyHelper
    arguments: []
  tvshows_config.view_helper:
    class: Drupal\tvshows_config\Services\ViewHelper
    arguments: ["@tvshows_config.taxonomy_helper"]
