name: tvshows_config
type: module
core: 8.x
dependencies:
  - comment
  - datetime
  - field
  - file
  - image
  - media
  - menu_ui
  - node
  - path
  - pathauto
  - rdf
  - taxonomy
  - text
  - user
  - views
