name: 'Tv Shows Config'
description: 'Module that provides the configuration for tvshow websites.'
package: 'Tv Show'
type: module
core: 8.x
dependencies:
  - block
  - comment
  - ctools
  - datetime
  - field
  - file
  - image
  - link
  - media
  - media_library
  - menu_ui
  - metatag
  - node
  - path
  - pathauto
  - rabbit_hole
  - rdf
  - responsive_image
  - system
  - taxonomy
  - text
  - tvshows_config
  - user
  - views
